### Importing Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Reading csv file

In [2]:
poke = pd.read_csv('pokemon.csv')

### Exploring the data

In [3]:
poke.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    object
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    object
 24  classfication      801 non-null    object
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    object
 30  name               801 non-null    object
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    object
 37  type2              417 non-null    object
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), object(7)
memory usage: 256.7+ KB

In [4]:
poke.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [5]:
poke.shape

(801, 41)

In [6]:
poke.describe()

,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,against_grass,...,height_m,hp,percentage_male,pokedex_number,sp_attack,sp_defense,speed,weight_kg,generation,is_legendary
count,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,801.000000,...,781.000000,801.000000,703.000000,801.000000,801.000000,801.000000,801.000000,781.000000,801.000000,801.000000
mean,0.996255,1.057116,0.968789,1.073970,1.068976,1.065543,1.135456,1.192884,0.985019,1.034020,...,1.163892,68.958801,55.155761,401.000000,71.305868,70.911361,66.334582,61.378105,3.690387,0.087391
std,0.597248,0.438142,0.353058,0.654962,0.522167,0.717251,0.691853,0.604488,0.558256,0.788896,...,1.080326,26.576015,20.261623,231.373075,32.353826,27.942501,28.907662,109.354766,1.930420,0.282583
min,0.250000,0.250000,0.000000,0.000000,0.250000,0.000000,0.250000,0.250000,0.000000,0.250000,...,0.100000,1.000000,0.000000,1.000000,10.000000,20.000000,5.000000,0.100000,1.000000,0.000000
25%,0.500000,1.000000,1.000000,0.500000,1.000000,0.500000,0.500000,1.000000,1.000000,0.500000,...,0.600000,50.000000,50.000000,201.000000,45.000000,50.000000,45.000000,9.000000,2.000000,0.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,65.000000,50.000000,401.000000,65.000000,66.000000,65.000000,27.300000,4.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,...,1.500000,80.000000,50.000000,601.000000,91.000000,90.000000,85.000000,64.800000,5.000000,0.000000
max,4.000000,4.000000,2.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,14.500000,255.000000,100.000000,801.000000,194.000000,230.000000,180.000000,999.900000,7.000000,1.000000

In [7]:
poke.dtypes

abilities             object
against_bug          float64
against_dark         float64
against_dragon       float64
against_electric     float64
against_fairy        float64
against_fight        float64
against_fire         float64
against_flying       float64
against_ghost        float64
against_grass        float64
against_ground       float64
against_ice          float64
against_normal       float64
against_poison       float64
against_psychic      float64
against_rock         float64
against_steel        float64
against_water        float64
attack                 int64
base_egg_steps         int64
base_happiness         int64
base_total             int64
capture_rate          object
classfication         object
defense                int64
experience_growth      int64
height_m             float64
hp                     int64
japanese_name         object
name                  object
percentage_male      float64
pokedex_number         int64
sp_attack              int64
sp_defense             int64
speed                  int64
type1                 object
type2                 object
weight_kg            float64
generation             int64
is_legendary           int64
dtype: object

In [8]:
poke.count()

abilities            801
against_bug          801
against_dark         801
against_dragon       801
against_electric     801
against_fairy        801
against_fight        801
against_fire         801
against_flying       801
against_ghost        801
against_grass        801
against_ground       801
against_ice          801
against_normal       801
against_poison       801
against_psychic      801
against_rock         801
against_steel        801
against_water        801
attack               801
base_egg_steps       801
base_happiness       801
base_total           801
capture_rate         801
classfication        801
defense              801
experience_growth    801
height_m             781
hp                   801
japanese_name        801
name                 801
percentage_male      703
pokedex_number       801
sp_attack            801
sp_defense           801
speed                801
type1                801
type2                417
weight_kg            781
generation           801
is_legendary         801
dtype: int64

In [9]:
poke['type1'].value_counts()

water       114
normal      105
grass        78
bug          72
psychic      53
fire         52
rock         45
electric     39
poison       32
ground       32
dark         29
fighting     28
dragon       27
ghost        27
steel        24
ice          23
fairy        18
flying        3
Name: type1, dtype: int64

In [10]:
poke['type2'].value_counts()

flying      95
ground      34
poison      34
fairy       29
psychic     29
fighting    25
steel       22
dark        21
grass       20
dragon      17
water       17
ice         15
ghost       14
rock        14
fire        13
electric     9
bug          5
normal       4
Name: type2, dtype: int64

In [11]:
poke['generation'].value_counts()

5    156
1    151
3    135
4    107
2    100
7     80
6     72
Name: generation, dtype: int64

In [12]:
poke['type1'].unique()

array(['grass', 'fire', 'water', 'bug', 'normal', 'poison', 'electric',
       'ground', 'fairy', 'fighting', 'psychic', 'rock', 'ghost', 'ice',
       'dragon', 'dark', 'steel', 'flying'], dtype=object)

### Data Pre-processing

In [24]:
total = poke.isnull().sum().sort_values(ascending=False)
percent = (poke.isnull().sum()/poke.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent],axis=1, keys=['Total','Percent'])
missing_data.head(41)

                   Total  Percent
abilities              0      0.0
base_happiness         0      0.0
capture_rate           0      0.0
classfication          0      0.0
defense                0      0.0
experience_growth      0      0.0
height_m               0      0.0
hp                     0      0.0
japanese_name          0      0.0
name                   0      0.0
percentage_male        0      0.0
pokedex_number         0      0.0
sp_attack              0      0.0
sp_defense             0      0.0
speed                  0      0.0
type1                  0      0.0
type2                  0      0.0
weight_kg              0      0.0
generation             0      0.0
base_total             0      0.0
base_egg_steps         0      0.0
against_bug            0      0.0
attack                 0      0.0
against_dark           0      0.0
against_dragon         0      0.0
against_electric       0      0.0
against_fairy          0      0.0
against_fight          0      0.0
against_fire           0      0.0
against_flying         0      0.0
against_ghost          0      0.0
against_grass          0      0.0
against_ground         0      0.0
against_ice            0      0.0
against_normal         0      0.0
against_poison         0      0.0
against_psychic        0      0.0
against_rock           0      0.0
against_steel          0      0.0
against_water          0      0.0
is_legendary           0      0.0

In [14]:
poke['type2'].fillna('None', inplace=True)

In [15]:
df1 = poke[poke.isna().any(axis=1)]
df1['name']

18        Rattata
19       Raticate
25         Raichu
26      Sandshrew
27      Sandslash
          ...
796    Celesteela
797       Kartana
798      Guzzlord
799      Necrozma
800      Magearna
Name: name, Length: 117, dtype: object

In [16]:
poke[poke['weight_kg'].isna()]['name']

18       Rattata
19      Raticate
25        Raichu
26     Sandshrew
27     Sandslash
36        Vulpix
37     Ninetales
49       Diglett
50       Dugtrio
51        Meowth
52       Persian
73       Geodude
74      Graveler
75         Golem
87        Grimer
88           Muk
102    Exeggutor
104      Marowak
719        Hoopa
744     Lycanroc
Name: name, dtype: object

In [17]:
poke[poke['height_m'].isna()]['name']

18       Rattata
19      Raticate
25        Raichu
26     Sandshrew
27     Sandslash
36        Vulpix
37     Ninetales
49       Diglett
50       Dugtrio
51        Meowth
52       Persian
73       Geodude
74      Graveler
75         Golem
87        Grimer
88           Muk
102    Exeggutor
104      Marowak
719        Hoopa
744     Lycanroc
Name: name, dtype: object

In [20]:
poke[poke['percentage_male'].isna()]['name'].unique()

array([], dtype=object)

In [21]:
poke['percentage_male'].fillna(100, inplace=True)

In [23]:
poke.dropna(inplace=True)